version: "2"

services:

    php:
        image: igorgsarmento/php5.6-apache
        ports:
            - "80:80"
        
        environment:
            DB_HOST: mysql
            DB_DATABASE: abrace_pets
            DB_USERNAME: abracepets
            DB_PASSWORD: abracepets
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        links:
            - mysql

    mysql:
        image: mysql:5.7
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: abrace_pets
            MYSQL_USER: abracepets
            MYSQL_PASSWORD: abracepets
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - mysql-data:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - mysql
        links:
            - mysql

volumes:
    mysql-data: